### ISSUE TITLE
makeglossaries não roda no Windows 10 (Miktex 2.9)

### ISSUE THREAD

**Issue by kauerodrigues** [douglasrizzo/Classe-Latex-FEI#15]
a ultima atualização não esta rodando no miktex 2.9 (windows 10)

e na penúltima versão...
não gera de forma alguma a lista de símbolos e siglas...por fim consegui fazer sair a lista de siglas, apos instalar o texmaker, porem o cabeçalho "SIGLAS" fica alinhado a esquerda.

com a ajuda fundamental do André, consegui gerar ambas as listas após instalar um package ActivePerl-5.20.2.2002-MSWin32-x64-299195...porem minha maquina ficou extremamente lenta, principalmente para ligar e desligar...por fim, retirei esse package e tive ainda que restaurar a maquina para voltar ao normal...

**Comment by douglasrizzo** [comment]
O script `makeglossaries` que é chamado no prompt de comando do Windows, ou pela aplicação que esteja sendo usada pra compilar, é um script em Perl. Não tem como rodar o script sem ter a linguagem instalada.

Alguns links úteis sobre o erro:
http://tex.stackexchange.com/questions/158796/miktex-and-perl-scripts-and-one-python-script
http://tex.stackexchange.com/questions/25950/how-to-use-makeglossaries

No Mac e no Linux, o Perl já vem instalado. O Windows tem o Active Perl, que parece que foi o que tu instalou, além do Strawberry Perl e outros. Cada distribuição tem uma finalidade específica, mas eu não sei qual a melhor O [site do Perl](https://www.perl.org/get.html) tem uma lista de distribuições.

**Comment by kauerodrigues** [comment]
E ae Douglas.

então, os links que vc me passou são os que eu estava usando para corrigir o meu problema...
tentei fazer algumas das sugestões de outros fóruns, porem em todas a minha maquina com windows 10 ficou extremamente lenta...nao sei mais como resolver isso...rs
bom, quanto a ultima atualização da classe, nao sei pq, mas nao estou conseguindo usa-la...

**Comment by RodrigoPrior** [comment]
vc chegou a testar o Strawberry Perl?

**Comment by kauerodrigues** [comment]
acabei de tentar...depois de reiniciar a maquina 2 vezes ela voltou a ficar rápida, porem nao esta gerando a lista de figuras e abreviaturas...vou tentar mais amanhã a noite na FEI...muito obrigado pela ajuda...

**Comment by RodrigoPrior** [comment]
legal...mas no seu build do latex nao volta nenhuma mensagem de erro ou warning? qual editor vc usa?

**Comment by douglasrizzo** [comment]
O problema não pode ser na classe. Que nem eu falei, o `makeglossaries` precisa do Perl pra rodar (eu nem sabia disso, no Linux o Perl vem instalado por padrão). Pra instalar Perl no Windows, todo o mundo recomenda Active Perl ou Strawberry Perl. Eu parei de usar Windows quando estava no 7, então não posso te ajudar com problemas relacionados ao Windows 10.

Eu descobri hoje que [dá pra usar o *xindy* no Windows agora](http://tex.stackexchange.com/questions/71167/how-to-use-xindy-with-miktex). Se você quiser tentar, é só adicionar a opção `xindy` na declaração da classe. O *xindy* também depende de Perl, que nem menciona o link aí em cima, mas ele compila as listas de símbolos e abreviaturas com outro programinha (*texindy* ao invés de *makeindex*).

**Comment by kauerodrigues** [comment]
Douglas e Rodrigo,

Problema resolvido!!!

Falei com o André (ele me ajudou muito nesse problema) e acreditamos que seria indicado colocarmos algumas notas para usuários windows na classe...

Estava usando o miktex conforme indicado na classe, porem esse não reconhecia o makeglossary. Após algumas tentativas de Perl correto (outras versões deixaram a minha máquina extremamente lenta), instalei o Strawberry Perl conforme indicado por vcs, porém o miktex continuou não fazendo o makeglossary. o André achou o link abaixo de um fórum de discussão sobre o assunto e indicavam instalar o texmaker como ferramenta de edição e editar o processo de copilação da seguinte forma:

Usuarios ---->Comandos do usuário--->Editar comandos de usuário--->no comando 1, colocar no item Menu o nome makeglossary (ou qualquer outro a sua escolha)----> e item comando copiar e colar a seguinte linha: "pdflatex %.tex | bibtex %.aux | makeglossaries % | pdflatex %.tex | makeindex %.idx | pdflatex %.tex" 

Pronto!!! ao copilar, nao esquecer de chamar o comando que acabou de criar!!! 

http://tex.stackexchange.com/questions/61099/using-texmaker-with-glossaries-on-windows

Muito obrigado a todos pela ajuda.

Abraço
Kaue

**Comment by douglasrizzo** [comment]
Assim que eu colocar no manual que esses scripts dependem do Perll, eu fecho esse bug aqui.

**Comment by liviafperes2017** [comment]
Olá Estou acompanhando a discussão de vocês , estou usando o texstudio para minha tese , tentei migrar pro texmaker mas parece que o meu template não funciona nele acaba desconfigurando totalmente (é o template da coppe com algumas alterações pessoais).
O meu glossary nao funciona de modo algum! Já instalei o Strawberry Perl  e mais um compilador de Perl, mas ainda assim não estou conseguindo fazer rodar. Tentei replicar estas últimas configurações sugeridas :

{o Menu--->Usuarios ---->Comandos do usuário--->Editar comandos de usuário--->selecione o comando 1, colocar no item Menu o nome makeglossary (ou qualquer outro a sua escolha)----> e item comando copiar e colar a seguinte linha: "pdflatex %.tex | bibtex %.aux | makeglossaries % | pdflatex %.tex | makeindex %.idx | pdflatex %.tex" . (essa linha de comando já estava no manual da classe como sendo "o jeito difícil" de copilar o projeto)}


travou completamente meu texstudio , de uma forma que tive que fechar o windows.

Não sei mais como tentar imprimir o glossário. Se vocês puderem me ajudar.

Obrigada!

**Comment by RodrigoPrior** [comment]
o q eh "template da coppe" ?

**Comment by liviafperes2017** [comment]
Rodrigo - Obrigada pela resposta =), 
O template que estou usando é o padrão da faculdade, meu orientador me passou ele e tenho que obrigatoriamente utilizar.

No caso é a Coppe-UFRJ.

**Comment by douglasrizzo** [comment]
@liviafperes2017 não entendi se a compilação já funcionava antes de você mudar de editor e parou de funcionar ou se ela nunca funcionou. Você leu o manual da classe que você está usando, a CoppeTeX? Você procurou o manual do pacote de glossários que ela usa (glossary, glossaries etc)? Seu glossário está escrito corretamente? Se você tirar ele, seu documento compila? Você tem o _log_ das compilações?

**Comment by douglasrizzo** [comment]
Aqui tem os [manuais do pacote glossaries](https://www.ctan.org/pkg/glossaries), que ensinam a criar listas de abreviaturas, símbolos etc., e o [manual da sua classe](http://coppetex.sourceforge.net/doc/coppe.pdf), se ela tiver alguma instrução específica.

**Comment by liviafperes2017** [comment]
Vou tentar explicar.
Meu código está compilando corretamente , contudo ao fazer o comando Tools => Glossary (comando requerido para compilar o glosário ) tenho o erro 

Process started: makeglossaries.exe "thesis_liviaperes"

No \@istfilename found in 'thesis_liviaperes.aux'. Did your LaTeX run fail? Did your LaTeX run produce any output? Did you remember to use \makeglossaries?

Process exited with error(s)

Mesmo colocando a \usepackage{glossaries} e os demais comandos corretamente, ele gera esse erro  mesmo criando o \makeglossary nas opções de build do Texstudio ele continua a gerar o mesmo erro.

Tentando solucionar o problema fiz o download do Pearl Package (o Strawberry também), mas ele continuava a apresentar vários erros como se não encontrasse o aquivo pearl necessário para a compilação. 

Mais acima na discussão o kauerodrigues  24/08/15 deixa uma sugestão de solução para o erro (utilizando o Texmaker, infelizmente não deu certo pra mim) , tentando aplicar esta solução no Texstudio ele travou completamente a máquina.

Ressetei as configurações do Texstudio e tudo voltou a funcionar , o erro voltou também e ainda estou sem glosário.

Obrigada pela força!

**Comment by liviafperes2017** [comment]
Como sou nova nesse tipo de programação fiquei com receio de utilizar o Xindy, mas acho que talvez ele possa solucionar a questão.

**Comment by douglasrizzo** [comment]
Provavelmente o editor que você usa está apagando os arquivos temporários depois de gerar o PDF com sucesso. Quando você roda o Glossary, ele procura esses arquivos, não acha e dá o erro, falando que sua compilação do LaTeX não teve _output_ nenhum. Por exemplo, ele pede pelo arquivo `thesis_liviaperes.aux`. Você vê esse arquivo na pasta? Em uma compilação bem-sucedida, ele sempre é gerado.

Já deixo aqui um disclaimer de que eu nunca usei LaTeX no windows, muito menos editores como TexMaker e TexStudio. Esses editores são famosos por compilarem do jeito que eles querem, então você nunca sabe muito bem o que eles fazem no plano de fundo.

**Comment by RodrigoPrior** [comment]
Vou ser bem sincero @liviafperes2017, sua duvida nao faz o menor sentido e essa thread nao deveria ser utilizada para resolve-la.

Vc deveria abrir um novo issue para que as respostas anteriores nao fossem desviadas para o seu problema particular, que não tem relação alguma com a pergunta inicial e muito menos com a classe-fei.

Ainda sim, o mais correto seria vc falar diretamente com os responsáveis pela classe "coppe" que vc esta utilizando ou perguntar para o seu orientador...que colocou vc nessa roubada ;)

**Comment by liviafperes2017** [comment]
colocou mesmo! Thanks!

**Comment by douglasrizzo** [comment]
Fazer índice e glossário é tenso mesmo. Como eu disse, não tenho experiência em fazer isso no Windows e acho que minhas dicas aí em cima são tudo o que eu posso fazer, já que não conheço a classe que você está usando. Vou fechar esse _issue_.
