### ISSUE TITLE
Posicionamento da legenda da imagem!

### ISSUE THREAD

**Issue by aislancesar** [douglasrizzo/Classe-Latex-FEI#22]
Douglas,

Na página 6 do manual da biblioteca, na parte sobre ilustrações está escrito:
Para qualquer tipo de ilustração (desenho, esquema, fotografia, gráfico, mapa, organograma, planta, quadro, retrato, figura e outros), sua identificação deve aparecer na parte superior, **ALINHADA À ESQUERDA DA ILUSTRAÇÃO E NÃO DA MARGEM**, com fonte 12, seguida de seu número de ordem de ocorrência no texto, em algarismo arábico, travessão e do título. A ilustração pode aparecer na margem esquerda ou centralizada.

Atualmente a classe está alinhando o texto à margem, e não à figura.

Atenciosamente,
Aislan...

**Comment by douglasrizzo** [comment]
Opa, adicionei no manual da classe, apêndice B, o hack de adicionar o `minipage` dentro do ambiente `figure`. Essa parece ser a solução correta para o nosso problema. Infelizmente, não dá pra redefinir o `figure` pra fazer isso automaticamente porque as pessoas podem querer usar o `figure` original pra algo, então, no futuro, vou ver se crio um novo ambiente.
