### ISSUE TITLE
Quadros e tabelas

### ISSUE THREAD

**Issue by filipimfs** [douglasrizzo/Classe-Latex-FEI#24]
Aparentemente existe uma diferença entre quadro (informação sem nenhum número) e tabela (um quadro com números). A bibliotecária pediu que eu arrumasse isso, mas a classe atual não permite.

**Comment by douglasrizzo** [comment]
O quadro existe quando um elemento é cercado por bordas em todos os lados. Se você tem uma tabela que a biblioteca considera um quadro, é possível transformá-la efetivamente numa tabela, por exemplo, removendo as bordas laterais. [Veja esse exemplo](https://bibliotecafea.com/2012/09/21/tabela-e-quadro-diferencas/).

A classe não suporta a criação de listas de outros _floats_ que não aqueles listados no manual (figura, tabela, algoritmo etc).
