### ISSUE TITLE
Ilustrações vs. Figuras

### ISSUE THREAD

**Issue by filipimfs** [douglasrizzo/Classe-Latex-FEI#25]
No corpo do texto a legenda apresenta a palavra "figura X", enquanto na lista de ilustrações a palavra que aparece é  "Ilustração X". A bibliotecária pediu para que eu arrume isso.

**Comment by douglasrizzo** [comment]
No apêndice B do manual da versão 3.0.5 da classe (disponível aqui no GitHub e também no [CTAN](http://ctan.org/pkg/fei)) eu ensino como mudar os nomes das listas, assim como a forma como os elementos são nomeados dentro delas.

Isso depende muito da bibliotecária. Quando mostrei a classe pra elas da última vez, elas aceitaram que a lista fosse chamada de "Lista de Ilustrações", os elementos fossem chamados de "Ilustração" na lista e no texto fossem chamados de "Figura".
