### ISSUE TITLE
 File 'brazilian-abnt-abnt.lbx' not found!

### ISSUE THREAD

**Issue by Lucassalgueiro** [douglasrizzo/Classe-Latex-FEI#32]
Pode ser um problema muito basico, mas passei bastante tempo sem usar o Latex e mesmo quando usava nunca fui muito bom. Estou tentando usar a classe fei para criar meu documento mas, embora consigo compilar sem problemas, recebo esta mensagem de aviso constantemente apos cada compilacao

Package biblatex Warning: File 'brazilian-abnt-abnt.lbx' not found!
(biblatex) Ignoring mapping 'brazilian-abnt' -> 'brazilian-abnt-
abnt'.
Package biblatex Info: Trying to load language 'brazilian-abnt'...
Package biblatex Info: ... file 'brazilian-abnt.lbx' found.

onde posso adquirir tais arquivos ? na propria mensagem de erro vejo o caminho do arquivo porem nao tenho ideia de ondei baixa-lo.

novamente, peco desculpas pela pergunta de iniciante.

**Comment by douglasrizzo** [comment]
Fala Lucas. Estes arquivos que você mencionou são relacionados com a geração de citações e referências bibliográficas. Mas não deve ser um erro, e sim um aviso, porque de acordo com a mensagem que você disponibilizou:

1. não foi achado o arquivo `brazilian-abnt-abnt.lbx`;
2. o biblatex (um pacote que que a classe da FEI usa) ignorou essa configuração;
3. e acabou encontrando e usando o arquivo `brazilian-abnt.lbx`.

Moral da história, não deve estar acontecendo nenhum erro na sua compilação.

Se você quiser checar com certeza, referencie um arquivo `.bib` no seu trabalho (com o comando `\addbibresource`), inclua algumas citações (com `\cite`, `\textcite` etc.), mande imprimir as referências (com `\printbibliography`) e compile. Se as citações e referências aparecerem corretamente, está tudo certo. Ou então, tente compilar o template e veja o resultado.

**Comment by Lucassalgueiro** [comment]
Sinto muito, eu nao sei o que seria "compilar o template". eu tentei fazer o teste. Coloquei um arquivo "ref.bib" na pasta raiz do meu documento, usar o comando` \addbibresource{ref.bib}` porem quando tento compilar recebo o erro LaTeX Warning: Citation 'eisberg1974quantum' on page 9 undefined on input line com ambos os comandos `\cite{eisberg1974quantum}` `\textcite{eisberg1974quantum}`. e consequentemente o erro "empty bibliography" aparece. tenho nas configuracoes do TexMaker como biblatex o biber...seria esse o problema ? (o proprio arquivo do biber tambem se enccontra na pasta raiz do documento)

**Comment by douglasrizzo** [comment]
Bom, eu tenho várias perguntas.

1. qual programa você está usando pra escrever seu trabalho? (Texmaker, Texstudio, Overleaf...)
2. qual sistema operacional você está usando?
3. você tem `eisberg1974quantum` no seu arquivo `ref.bib`? Se não, ele precisa estar lá.
4. você está usando o `biber` na compilação do seu trabalho? Cheque a seção 6 do [manual da classe da FEI](http://mirrors.ctan.org/macros/latex/contrib/fei/fei.pdf). Pode ser que você esteja usando um editor de texto que não está executando todos os passos necessários para gerar o PDF completo.

Por último, dê uma olhada [neste post](https://groups.google.com/forum/#!topic/grupo-latex-fei/CmJgGQiFZy4) que eu fiz com dúvidas frequentes dos usuários.

**Comment by Lucassalgueiro** [comment]
1 - TexMaker
2 - Windows 10 Home
3 - tenho sim, nesse formato
```
@book{eisberg1974quantum,
  title={Quantum physics},
  author={{Eisberg, Robert and Resnick, Robert}},
  year={1974},
  publisher={John Wiley New York}
  
}
```
4 - Obrigado  pela dica aqui, eu estava usando a opcao Quick Build > View PDF, mas me esqueci de reconfigurar o quick build quando formatei o computador, os comando executados estavam sendo apenas PDFLATE > VIEW PDF, reconfigurei para **_PdfLaTeX+Bib(la)tex+PdfLaTeX(x2)+Vew PDF_** e funcionou perfeitamente
5- Esse grupo nao existe pra mim por algum motivo "This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access." Como faco para ter acesso ?

Agradeco por toda a ajuda, como para compilar as referencias demora significativamente mais, deixarei esse metodo apenas  para o final (sei que existe uma forma mais rapida usando o comando `\include` mas como sou iniciante ainda e por medo de complicar ainda mais as coisas, estou usando apenas um unico script mesmo)

**Comment by douglasrizzo** [comment]
Tente pedir para ser aceito no grupo através [deste link](https://groups.google.com/forum/#!forum/grupo-latex-fei).

Por via das dúvidas, eu acabei passando as dicas que estavam no Google Groups para o GitHub e você pode lê-las [aqui]/(https://github.com/douglasrizzo/Classe-Latex-FEI/wiki).
