### ISSUE TITLE
Nome das seções não estão em letra maiúscula no sumário

### ISSUE THREAD

**Issue by leonardoSCosta** [douglasrizzo/Classe-Latex-FEI#35]
O problema pode ser visto na imagem abaixo.
![image](https://user-images.githubusercontent.com/37155964/204402073-2bd92059-6d68-4a84-bd83-e891090e4bde.png)

Eu consegui resolver o problema fazendo esta modificação no arquivo da classe fei.

`
\renewcommand{\cftsectionfont}{\uppercase}
`
Esta linha foi adicionada na linha n⁰ 461 do arquivo fei.cls, o resultado final foi esse:

```
\renewcommand{\cftchapterfont}{\bfseries} % coloca o titulo de capítulos em negrito
\renewcommand{\cftsectionfont}{\uppercase} % solução encontrada
\renewcommand{\cftsubsectionfont}{\bfseries} % coloca o titulo das secoes em negrito
\renewcommand{\cftsubsubsectionfont}{\bfseries\itshape} % coloca o titulo das secoes em negrito
\renewcommand{\cftparagraphfont}{\itshape} % coloca o titulo das secoes em negrito
```
No arquivo ficou assim:
![image](https://user-images.githubusercontent.com/37155964/204402554-da86eda1-dadf-499d-b565-399453bd83d0.png)

**Comment by douglasrizzo-adroit** [comment]
Legal. Eu encontrei um comentário na classe relevante pra esse problema, onde eu tentei usar `\MakeTextUppercase` ao invés de `\uppercase`.

https://github.com/douglasrizzo/Classe-Latex-FEI/blob/ed48f88ead17e7023a750fcd479cf94519f3b438/fei.dtx#L2083-L2097

**Comment by douglasrizzo** [comment]
Legal. Eu encontrei um comentário na classe relevante pra esse problema, onde eu tentei usar `\MakeTextUppercase` ao invés de `\uppercase`.

https://github.com/douglasrizzo/Classe-Latex-FEI/blob/ed48f88ead17e7023a750fcd479cf94519f3b438/fei.dtx#L2083-L2097
